export enum Colors {
  WHITE = 'white',
  MEDIUM_GRAY = 'medium-gray',
  MEDIUM_GRAY_LIGHT = 'medium-gray-light',
  GRAY_LIGHT = 'gray-light',
  GRAY = 'gray',
  SPRING_GREEN = 'spring-green',
  SPRING_GREEN_LIGHT = 'spring-green-light',
  GREEN_LIGHT = 'green-light',
  DUSTY_GREEN = 'dusty-green',
  SALMON_PINK = 'salmon-pink',
  SALMON_PINK_LIGHT = 'salmon-pink-light',
  SALMON_PINK_DARK = 'salmon-pink-dark',
  DUSTY_ROSE = 'dusty-rose',
  BABY_BLUE = 'baby-blue',
  DUSTY_BLUE = 'dusty-blue',
  CHARCOAL_GRAY = 'charcoal-gray',
  MIDNIGHT_BLUE = 'midnight-blue',
  SPACE_BLACK = 'space-black',
  APP_X = 'x',
  APP_TELEGRAM = 'telegram',
  APP_GITHUB = 'github',
  APP_YELLOW = 'yellow',
}
